### ISSUE TITLE
Create Searchbar component

### ISSUE THREAD

**Issue by hhimanshu** [forkfacts/forkfacts#18]
The design file is available at [Figma](https://www.figma.com/file/nhyeaTsg4Jhhzq2PwuvnGk/forkfacts?node-id=867%3A10166)

![image](https://user-images.githubusercontent.com/6589036/136615502-800ca0ab-efb5-4a63-8606-61515f424f4d.png)

What to build?  
- [ ] A component
- [ ] A storybook story accompanying the component

**Comment by deekshasharma** [comment]
This is completed as part of #64
